### ISSUE TITLE
getAllResponseHeaders and getResponseHeader return request headers

### ISSUE THREAD

**Issue by wezm** [KhafraDev/node-xmlhttprequest#1]
https://github.com/KhafraDev/node-xmlhttprequest/blob/f44a503dbb3d03bffba81e905b987611ed557553/src/xmlhttprequest.js#L856-L893

Both are accessing `this[kRequestHeaders]`. I think they should be using `this[kResponse].headersList`.

**Comment by KhafraDev** [comment]
didn't notice your PR, the bugs should be fixed now, thanks!
